train_data_root: /tmp/surgery-scene-graphs/cholecseg8k_sasvi_train
data_staging:
  use_ram: true
  ram_train_data_root: /dev/shm/surgery-scene-graphs/cholecseg8k_sasvi_train
log_dir: output/segment/maskrcnn_cholecseg
checkpoint_filename: best_val_dice.pth

prediction_subdir: semantic_masks_sasvi_orig_res

run_training: false
run_inference: true

# checkpoint_path: output/segment/maskrcnn_cholecseg/[latest]/best_val_dice.pth
checkpoint_path: output/segment/maskrcnn_cholecseg/best_val_dice.pth

backbone: ResNet50
hidden_ft: 64
trainable_backbone_layers: 3
num_train_classes: 13

train:
  epochs: 500
  steps: 200 # limits iterations per epoch if not -1
  val_freq: 5
  batch_size: 8
  num_workers: 4
  weighted_sampling: false
  weighted_loss: false
  initial_lr: 0.0001
  betas: [0.5, 0.999]
  weight_decay: 0.05
  scheduler_step_size: 100
  scheduler_gamma: 0.5
  img_size: [299, 299]
  img_norm: [0.0, 1.0]
  ignore_ids: [0]
  shift_ids_by_1: true
  components: false
  min_comp_fraction: 0.05

sasvi:
  sam2_cfg: configs/sam2.1_hiera_l.yaml
  sam2_checkpoint: submodules/SASVi/src/sam2/checkpoints/sam2.1_hiera_large.pt
  overseer_type: MaskRCNN
  dataset_type: CHOLECSEG8K
  base_video_dir: output/segment/sasvi/base_video_dir
  output_mask_dir: output/segment/sasvi/output_masks
  dump_overseer_masks: false
  overseer_mask_dir: output/segment/sasvi/overseer_masks
  score_thresh: 0.0
  apply_postprocessing: false
  save_binary_mask: false

device: cuda
