graph_output_subdir: graph

load_stage: fine-lang
iteration: -1

# TODO we likely want to filter initially based on opacity * instance feature norm
opacity_threshold: 0.05
inst_feat_norm_threshold: 0.05

clustering_weights:
  position: 1.0  # Weight spatial features more than instance features
  instance: 2.0  # Reduce this if instance features are poorly trained (e.g., 0.5 or 0.1)
cluster_min_size: 150  # Larger values = fewer, larger clusters
cluster_min_samples: 150  # Larger values = more conservative clustering
cluster_metric: euclidean

min_gaussians_per_cluster: 150 # TODO this is redundant with hdbscan min cluster size

max_features_per_cluster: 40
min_features_per_cluster: 4
decode_batch_size: 1024

n_timesteps: 15 # graph timesteps

graph_edge_threshold: 0.05 # minimum bhattacharyya coefficient to create an edge between clusters

store_verbose: true  # save verbose outputs (renders, palettes, raw gaussians, etc.)
n_render_views: 1  # number of random camera views to render (only if store_verbose is true)

random_seed: 1234

# spatial grounding feature extraction
spatial_grounding:
  n_splat_points: 1000
  n_cluster_points: 100

# TODO rendering based cluster filtering etc. have to be integrated here

language_feature_hiddendim: ${splat.language_feature_hiddendim}
use_discrete_lang_f: ${splat.use_discrete_lang_f}
config_path: ${splat.config_path}
dynamic_language: ${splat.dynamic_language}
latent_cat_feat_subdir: ${splat.latent_cat_feat_subdir}

checkpoint_subdir: ${autoencoder.checkpoint_subdir}
full_dim: ${autoencoder.full_dim}
latent_dim: ${autoencoder.latent_dim}