defaults:
  - temporal: default
  - spatial: default
  - directional: default
  - _self_

# temporal: null
# spatial: null
# directional: null

annotations_root: data/annotations

video_fps: ${eval.video_fps}
annotation_stride: ${eval.annotation_stride}
n_timesteps: ${eval.n_timesteps}

# Required output directory for benchmark results
output_dir: ${output_root}/metrics_final