defaults:
  - clips: t50_seg8k_intersection
  - preprocessing: default
  # - feature_extraction: default
  # - autoencoder: default
  # - splat: default
  # - graph_extraction: default
  - _self_

cholec80_root: data/cholec80
cholecseg8k_root: data/cholecseg8k
cholect50_root: data/cholect50
preprocessed_root: data/preprocessed_tmpttest

hydra:
  job:
    chdir: false