defaults:
  - clips: multiple
  - preprocessing: default
  - feature_extraction: qwen25
  - autoencoder: qwen25
  - splat: default
  - graph_extraction: default
  - eval: default
  - _self_

cholec80_root: data/cholec80
cholecseg8k_root: data/cholecseg8k
cholect50_root: data/cholect50
preprocessed_root: data/multiple
output_root: output/multiple

whole_pipeline_clips_sequentially: true  # do everything for each clip first if true, otherwise steps sequentially

config_dumps:
  - ${preprocessed_root}/config.yaml
  - ${output_root}/config.yaml

hydra:
  job:
    chdir: false