defaults:
  - clips: cholec80_clip #final_dataset_first
  - segment: sasvi_maskrcnn
  - preprocess: sasvi_masks
  - extract_geometry: default
  - track_objects: sasvi_masks
  - graph_extraction: sasvi_masks
  - eval: default
  - compute_metrics: default
  - _self_
  
cholecseg8k_root: /home/data/long_form_surgery_Cholec80/1fps_samples/  # /home/data/tumai/splatgraph/data/cholecseg8k

preprocessed_root: /home/data/tumai/splatgraph/data/preprocessed/clean/test_output
output_root: /home/data/tumai/splatgraph/data/output/

seed: 1234

config_dumps:
  # - ${output_root}/config.yaml

hydra:
  job:
    chdir: false