semantic_mask_subdir: semantic_masks
instance_mask_subdir: instance_masks
depth_subdir: depth

spatial_labels_root: data/spatial_labels
spatial_labels_input_filename_template: "{clip_name}_spatial.json"
spatial_labels_output_filename: "spatial_labels.json"
dump_label_visualizations: true
label_viz_subdir: label_viz

frames_divisor: 28 # after removing black borders, center crop to multiple of this for qwen to work

vipe_vda: true # use video depth anything
vipe_save_viz: false

vipe_slam_map: false # use slam map as pointcloud instead of aggregated depth projections
pc_single_depth_projection: true # use single depth projection based on instance count and depth range
pc_single_depth_use_instance_count: true # prioritize frames with more instances in the instance mask
vipe_depth_step: 16 # stride for depth maps that end up in pointclouds, only used if pc_single_depth_projection is false and vipe_slam_map is false

# Frame selection criteria for single depth projection (sorts by instance count first, then depth range as tie-breaker)

verbose_output: false # keep intermediate output files (mostly vipe)

min_component_area: 5 # minimum area of a component to be considered an instance